### ISSUE TITLE
CSS optmizer

### ISSUE THREAD

**Issue by hallodom** [less/less.ruby#187]
Hi, are there any plans to incorporate a css optimiser option? I find myself avoiding features in Less such as inheritance because I'm aware that they aren't optimised and repeats redundant declarations. 

Less example:

``` CSS
 .strong { background:#31343b; color:white; font-weight:normal; padding:2px 10px; margin-right:10px; }
 .small { .strong; background:#ff0000; }
```

Compliles to: 

``` CSS
.strong {
  background: #31343b;
  color: white;
  font-weight: normal;
  padding: 2px 10px;
  margin-right: 10px;
}
.small {
  background: #31343b;
  color: white;
  font-weight: normal;
  padding: 2px 10px;
  margin-right: 10px;
  background: #ff0000;
}
```

When optimised it should be: 

``` CSS
.strong,.small{background:#31343b;color:white;font-weight:normal;padding:2px 10px;margin-right:10px}
.small{background:#ff0000}
```
