### ISSUE TITLE
Parametric Mixin with parameter as CSS property name

### ISSUE THREAD

**Issue by mrmartineau** [less/less.ruby#188]
I've been experimenting with REMs today & have created a few mixins that have pixel fallbacks to cater for older browsers. Here's one for font-size:

``` css
.font-size(@sizeValue: @baseFontSize){
    @pxValue: @sizeValue;
    @remValue: (@sizeValue / 16);
    font-size: ~"@{pxValue}px";
    font-size: ~"@{remValue}rem";
}

usage:
.font-size(24);

output: 
font-size: 16px;
font-size: 1rem;

```

I found that I would also need one for line-height & then any other css property that might need a rem/px fallback, so I created this:

``` css
.rem(@property, @sizeValue){
    @pxValue: @sizeValue;
    @remValue: (@sizeValue / 16);
    @property: ~"@{pxValue}px";
    @property: ~"@{remValue}rem";
}

usage:
.rem(margin-bottom, 32);

output: 
margin-bottom: 30px;
margin-bottom: 2rem;
```

This assumes that my body font-size is 100% or 16px btw.

This second example did not work though, the LESS was compiled successfully but these mixins were not being compiled at all. **Could the fact that I want to use parameters as property name be the problem?**
