### ISSUE TITLE
nested pseudo selectors

### ISSUE THREAD

**Issue by manuelstofer** [less/less.ruby#197]
It would be nice to write psudo selectors in nested syntax:

``` less
a {
     color: red;
     :hover {
         color: blue;
     }
 }
```

Compiles currently to:

``` css
a {
  color: red;
}
a :hover {
  color: blue;
}
```

To support nested pseudo selector syntax the space before ':' should be removed:

``` css
a {
  color: red;
}
a:hover {
  color: blue;
}
```

**Comment by rjkip** [comment]
What about the following? This is already implemented.

``` less
a {
  &:hover {
    color: blue;
  }
}
```
