### ISSUE TITLE
Parsing @arguments and rgba colours

### ISSUE THREAD

**Issue by litera** [less/less.ruby#209]
I want a simple mixin:

``` less
.gradient(...) {
    @all: ~`"@{arguments}".replace(/[\[\]]/g,"").replace(/,\s+/g,",")`;
    @count: ~`"@{all}".match(/rgba\([^\)]+?\)[^,]*|[^,r]+/g).length`;
    @first: ~`"@{all}".match(/rgba\([^\)]+?\)|[^,r]+/g)[0]`;
    @last: ~`"@{all}".match(/rgba\([^\)]+?\)[^,]*|[^,r]+/g)[@{count}-1].split(/\s/g)[0]`;

    // browsers that don't support gradients
    background-colour: mix(@first, @last);
    // the rest winners
    background-image: linear-gradient(to bottom, @all);
}
```

I've been parsing first and last colour values in gradient definition to get either `#xxxxxx` value or `rgba(x,x,x,x)` out of it. Both of them being strings of course.

Suppose this usage scenario:

```
.gradient(#000, fade(#fff, 50) 75%);
```
## Questions
1. Is it possible to get individual arguments without converting `@arguments` to string and manually parsing it uzsing regular expressions as I did?
2. how can I convert string `"rgba(x,x,x,y)"` to a colour or actual LESS call so I'd be able to use it in `mix` function? Doing this doesn't seem to work:
   
   ```
   mix(~"@{first}", ~"@{last}")
   ```

**Comment by litera** [comment]
### I've managed to create a viable solution

After some thinking and reading I've created a solution that works as expected. Until LESS provides different mechanisms to argument parsing this should be used. In its core it uses immediately executing Javascript anonymous functions (rather complex) that parse arguments and _spit out_ required results.

I've written a [detailed blog post](http://erraticdev.blogspot.com/2013/03/less-gradient-mixin-with-fallback-for-ie.html) about it with development Javascript code. I'm providing a minified version of **gradient with fallback LESS mixin** here for quick use:

``` less
.gradient (...) {
    @all: ~`"@{arguments}".replace(/[\[\]]/g,"")`;
    @mix1: ~`(function(a){a=a.replace(/,\s+(?=[\d ,.]+\))/gi,";").split(/,\s*/g);var f=a[0].split(/\s+/g)[0];var l=a.pop().split(/\s+/g)[0];var c=function(c){var r=[];/rgb/i.test(c)&&c.replace(/[\d.]+/g,function(i){r.push(1*i);return"";});/#.{3}$/.test(c)&&c.replace(/[\da-f]/ig,function(i){r.push(parseInt(i+i,16));return"";});/#.{6}/.test(c)&&c.replace(/[\da-f]{2}/ig,function(i){r.push(parseInt(i,16));return"";});if(r.length)return r;return[100,0,0];};var p=function(v){return("0"+v.toString(16)).match(/.{2}$/)[0];};f=c(f);l=c(l);var r={r:((f.shift()+l.shift())/2)|0,g:((f.shift()+l.shift())/2)|0,b:((f.shift()+l.shift())/2)|0};return"#"+p(r.r)+p(r.g)+p(r.b);})("@{arguments}")`;
    @mix2: ~`(function(a){a=a.replace(/,\s+(?=[\d ,.]+\))/gi,";").split(/,\s*/g);var f=a[0].split(/\s+/g)[0];var l=a.pop().split(/\s+/g)[0];var c=function(c){var r=[];/rgb/i.test(c)&&c.replace(/[\d.]+/g,function(i){r.push(1*i);return"";});/#.{3}$/.test(c)&&c.replace(/[\da-f]/ig,function(i){r.push(parseInt(i+i,16));return"";});/#.{6}/.test(c)&&c.replace(/[\da-f]{2}/ig,function(i){r.push(parseInt(i,16));return"";});if(r.length){r.push(1);return r;}return[100,0,0,1];};f=c(f);l=c(l);var r={r:((f.shift()+l.shift())/2)|0,g:((f.shift()+l.shift())/2)|0,b:((f.shift()+l.shift())/2)|0,a:(f.shift()+l.shift())/2};return"rgba("+r.r+","+r.g+","+r.b+","+r.a+")";})("@{arguments}")`;
    background-color: @mix1;
    background-color: @mix2;
    background-image: -webkit-linear-gradient(top, @all);
    background-image: -moz-linear-gradient(top, @all);
    background-image: -o-linear-gradient(top, @all);
    background-image: linear-gradient(to bottom, @all);
}
```
