### ISSUE TITLE
Comments in between multiple background definition 

### ISSUE THREAD

**Issue by mohsen1** [less/less.ruby#222]
When I add comment after each background definition it doesn't compile to what I expect.

For example:

``` css
foo {
  background-image:
    url(blah.png), //one
    url(bar.png);  //two
}
```

compiles to 

``` css
foo {
  background-image: url(blah.png), //one url(bar.png);
}

```

I think this is a bug.
